### ISSUE TITLE
pip install enaml fails to build with python 2.7

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#234]
Sorry for spamming with issues.... It's also failing from master.

```
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    enaml/src/alias.cpp:361:28: warning: ‘_state’ defined but not used [-Wunused-variable]
     static struct module_state _state;
                                ^
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/enaml/src/alias.o -o build/lib.linux-x86_64-2.7/enaml/core/alias.so
    building 'enaml.core.declarative_function' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c enaml/src/declarative_function.cpp -o build/temp.linux-x86_64-2.7/enaml/src/declarative_function.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    enaml/src/declarative_function.cpp: In function ‘PyObject* DFunc_repr(DFunc*)’:
    enaml/src/declarative_function.cpp:159:51: error: format not a string literal and no format arguments [-Werror=format-security]
         return Py23Str_FromFormat( ostr.str().c_str() );
                                                       ^
    enaml/src/declarative_function.cpp: At global scope:
    enaml/src/declarative_function.cpp:494:28: warning: ‘_state’ defined but not used [-Wunused-variable]
     static struct module_state _state;
                                ^
    cc1plus: some warnings being treated as errors
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
   ```

```
enaml/src/declarative_function.cpp:159:51: error: format not a string literal and no format arguments [-Werror=format-security]
         return Py23Str_FromFormat( ostr.str().c_str() );

```

Installing `enaml==0.9.8` works .

**Comment by sccolbert** [comment]
What system/compiler?

**Comment by frmdstryr** [comment]
My laptop 

```
(venv) jrm@xps:~/Workspace/enaml$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
(venv) jrm@xps:~/Workspace/enaml$ uname -a
Linux xps 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

and on travis here https://travis-ci.org/codelv/enaml-native/jobs/303154679

**Comment by frmdstryr** [comment]
Changing it to `Py23Str_FromString` works but I don't know what that implies .

**Comment by frmdstryr** [comment]
This works

```cpp

#if PY_VERSION_HEX >= 0x03000000
    return Py23Str_FromFormat( ostr.str().c_str() );
#else
    return Py23Str_FromString( ostr.str().c_str() );
#endif

```

**Comment by sccolbert** [comment]
I'm not sure why I used used `Py23Str_FromFormat` there at all, since I'm not passing any formatting args. `Py23Str_FromString` should be fine, no `#if` directive required.

**Comment by frmdstryr** [comment]
Without the if, the python 3 tests fail:

```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.5.2, pytest-3.2.5, py-1.5.1, pluggy-0.4.0                                                                                                                         
PyQt5 5.9.1 -- Qt runtime 5.9.2 -- Qt compiled 5.9.2                                                                                                                                         
rootdir: /home/jrm/Workspace/enaml, inifile:                                                                                                                                                 
plugins: timeout-1.2.0, qt-2.2.1, cov-2.5.1, catchlog-1.2.2                                                                                                                                  
collected 208 items                                                                                                                                                                          
                                                                                                                                                                                             
tests/test_alias.py ....................................                                                                                                                                     
tests/test_comprehensions.py .......                                                                                                                                                         
tests/test_declarative_function.py ...                                                                                                                                                       
tests/test_encodings.py .......                                                                                                                                                              
tests/test_examples.py ......................s.............................s...s..F........s...                                                                                              
tests/test_q_resource_helpers.py .                                                                                                                                                           
tests/test_stylesheet.py ...........                                                                                                                                                         
tests/test_template.py ..................................................................                                                                                                    
tests/test_zipimporter.py .....                                                                                                                                                              
                                                                                                                                                                                             
========================================================================================= FAILURES ==========================================================================================
_____________________________________________________________________ test_examples[widgets/popup_view.enaml-handler59] _____________________________________________________________________
                                                                                                                                                                                             
enaml_qtbot = <pytestqt.qtbot.QtBot object at 0x7f9766633c50>, enaml_sleep = 0, path = 'widgets/popup_view.enaml', handler = <function handle_popup_view_example at 0x7f9771948378>

    @pytest.mark.parametrize("path, handler",
                             [('aliases/chained_attribute_alias.enaml', None),
                              ('aliases/chained_widget_alias.enaml', None),
                              ('aliases/simple_attribute_alias.enaml', None),
                              ('aliases/simple_widget_alias.enaml', None),
                              pytest.param('applib/live_editor.enaml', None,
                                           marks=pytest.mark.skipif(
                                               not SCINTILLA_AVAILABLE,
                                               reason='Requires scintilla')),
                              ('dynamic/conditional.enaml', None),
                              ('dynamic/fields.enaml', None),
                              ('dynamic/looper.enaml', None),
                              ('dynamic/notebook_pages.enaml', None),
                              ('functions/declare_function.enaml', None),
                              ('functions/observe_model_signal.enaml', None),
                              ('functions/override_function.enaml', None),
                              ('layout/basic/align_offset.enaml', None),
                              ('layout/basic/align.enaml', None),
                              ('layout/basic/grid.enaml', None),
                              ('layout/basic/hbox_equal_widths.enaml', None),
                              ('layout/basic/hbox_spacing.enaml', None),
                              ('layout/basic/hbox.enaml', None),
                              ('layout/basic/horizontal.enaml', None),
                              ('layout/basic/linear_relations.enaml', None),
                              ('layout/basic/vbox.enaml', None),
                              ('layout/basic/vertical.enaml', None),
                              pytest.param('layout/advanced/button_ring.enaml',
                                           None,
                                           marks=pytest.mark.skipif(
                                               not NUMPY_AVAILABLE,
                                               reason='Requires numpy')),
                              ('layout/advanced/factory_func.enaml', None),
                              ('layout/advanced/find_replace.enaml', None),
                              ('layout/advanced/fluid.enaml', None),
                              ('layout/advanced/manual_hbox.enaml', None),
                              ('layout/advanced/manual_vbox.enaml', None),
                              ('layout/advanced/nested_boxes.enaml', None),
                              ('layout/advanced/nested_containers.enaml', None),
                              ('layout/advanced/override_layout_constraints.enaml',
                               None),
                              ('stdlib/mapped_view.enaml', None),
                              ('stdlib/message_box.enaml', None),
                              ('stdlib/slider_transform.enaml', None),
                              ('stdlib/task_dialog.enaml', None),
                              ('styling/banner.enaml', None),
                              ('styling/dock_item_alerts.enaml', None),
                              ('styling/gradient_push_button.enaml', None),
                              ('templates/basic.enaml', None),
                              ('templates/advanced.enaml', None),
                              ('widgets/buttons.enaml', None),
                              ('widgets/context_menu.enaml', None),
                              ('widgets/dock_area.enaml', None),
                              ('widgets/dock_pane.enaml', None),
                              ('widgets/dual_slider.enaml', None),
                              ('widgets/file_dialog.enaml', None),
                              ('widgets/flow_area.enaml', None),
                              ('widgets/focus_traversal.enaml', None),
                              ('widgets/form_spacing.enaml', None),
                              ('widgets/form.enaml', None),
                              ('widgets/group_box.enaml', None),
                              ('widgets/h_group.enaml', None),
                              pytest.param('widgets/ipython_console.enaml', None,
                                           marks=pytest.mark.skipif(
                                               not IPY_AVAILABLE,
                                               reason=('Requires IPython and its '
                                                       'qt console.'))),
                              ('widgets/image_view.enaml', None),
                              ('widgets/main_window.enaml', None),
                              ('widgets/menu_bar.enaml', None),
                              pytest.param('widgets/mpl_canvas.enaml', None,
                                           marks=pytest.mark.skipif(
                                               not MATPLOTLIB_AVAILABLE,
                                               reason='Requires matplotlib')),
                              ('widgets/notebook.enaml', None),
                              ('widgets/popup_menu.enaml', None),
                              ('widgets/popup_view.enaml',
                               handle_popup_view_example),
                              ('widgets/progress_bar.enaml', None),
                              ('widgets/scroll_area.enaml', None),
                              ('widgets/slider.enaml', None),
                              ('widgets/spin_box.enaml', None),
                              ('widgets/splitter.enaml', None),
                              ('widgets/tool_bar.enaml', None),
                              ('widgets/tool_buttons.enaml', None),
                              ('widgets/v_group.enaml', None),
                              pytest.param('widgets/vtk_canvas.enaml', None,
                                           marks=pytest.mark.skipif(
                                               not VTK_AVAILABLE,
                                               reason='Requires vtk')),
                              ('widgets/window_children.enaml', None),
                              ('widgets/window_closing.enaml',
                               handle_window_closing),
                              ('widgets/window.enaml', None)])
    def test_examples(enaml_qtbot, enaml_sleep, path, handler):
        """ Test the enaml examples.
    
        """
        dir_path = os.path.abspath(os.path.split(os.path.dirname(__file__))[0])
        enaml_file = os.path.join(dir_path, 'examples', os.path.normpath(path))
    
        with open(enaml_file, 'rU') as f:
            enaml_code = f.read()
    
        # Parse and compile the Enaml source into a code object
        ast = parse(enaml_code, filename=enaml_file)
        code = EnamlCompiler.compile(ast, enaml_file)
    
        # Create a proper module in which to execute the compiled code so
        # that exceptions get reported with better meaning
        try:
            module = types.ModuleType('enaml_test')
            module.__file__ = os.path.abspath(enaml_file)
            sys.modules['enaml_test'] = module
            ns = module.__dict__
    
            # Put the directory of the Enaml file first in the path so relative
            # imports can work.
            sys.path.insert(0, os.path.abspath(os.path.dirname(enaml_file)))
            with imports():
                exec_(code, ns)
    
            window = ns['Main']()
            window.show()
            window.send_to_front()
            wait_for_window_displayed(enaml_qtbot, window)
            enaml_qtbot.wait(enaml_sleep*1000)
    
            if handler is not None:
>               handler(enaml_qtbot, window)

tests/test_examples.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_examples.py:74: in handle_popup_view_example
    popup_triggers[0].clicked = True
venv3/lib/python3.5/site-packages/enaml/core/declarative_meta.py:68: in declarative_change_handler
    engine.write(owner, change['name'], change)
venv3/lib/python3.5/site-packages/enaml/core/expression_engine.py:217: in write
    pair.writer(owner, name, change)
venv3/lib/python3.5/site-packages/enaml/core/standard_handlers.py:82: in __call__
    call_func(func, (), {}, scope)
examples/widgets/popup_view.enaml:116: in <module>
    clicked :: ConfigPopup(self).show()
venv3/lib/python3.5/site-packages/enaml/core/enamldef_meta.py:79: in __call__
    instance.__init__(parent, **kwargs)
venv3/lib/python3.5/site-packages/enaml/core/object.py:100: in __init__
    self.set_parent(parent)
venv3/lib/python3.5/site-packages/enaml/core/object.py:160: in set_parent
    parent.child_added(self)
venv3/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py:185: in child_added
    child.activate_proxy()
venv3/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py:210: in activate_proxy
    self.activate_top_down()
venv3/lib/python3.5/site-packages/enaml/widgets/toolkit_object.py:226: in activate_top_down
    self.proxy.activate_top_down()
venv3/lib/python3.5/site-packages/enaml/qt/qt_toolkit_object.py:76: in activate_top_down
    self.init_widget()
venv3/lib/python3.5/site-packages/enaml/qt/qt_popup_view.py:69: in init_widget
    self.set_arrow_edge(d.arrow_edge)
venv3/lib/python3.5/site-packages/enaml/core/declarative_meta.py:43: in __call__
    value = engine.read(owner, name)
venv3/lib/python3.5/site-packages/enaml/core/expression_engine.py:186: in read
    return pair.reader(owner, name)
venv3/lib/python3.5/site-packages/enaml/core/standard_handlers.py:101: in __call__
    return call_func(func, (tr,), {}, scope)
examples/widgets/popup_view.enaml:41: in <module>
    arrow_edge << arrow_edge.selected_item
venv3/lib/python3.5/site-packages/enaml/core/declarative_meta.py:43: in __call__
    value = engine.read(owner, name)
E   RecursionError: maximum recursion depth exceeded while calling a Python object
!!! Recursion detected (same locals & position)
====================================================================== 1 failed, 203 passed, 4 skipped in 8.30 seconds ======================================================================```

**Comment by frmdstryr** [comment]
Actually that error is the mysterious travis failure. If I run it a few times it eventually passes.

Perhaps it's related?

**Comment by sccolbert** [comment]
Unlikely to be related.

**Comment by frmdstryr** [comment]
Ok, yeah it seems to make no difference. So the switch to `Py23Str_FromString` at least fixes 2.7.

**Comment by frmdstryr** [comment]
Thanks
