### ISSUE TITLE
Python function on enaml file with multiple kwargs causes parser to crash.

### ISSUE THREAD

**Issue by gabrielcnr** [nucleic/enaml#251]
I've created a new environment with the latest version of `enaml` (`0.10.1`) pulled from `conda-forge` channel, using Python `2.7.14` on my Mac OS (I also verified the potential bug on Windows too).

I found out if I have a Python function defined on the `.enaml` module with 2 specified keyword arguments with defaults alongside the optional `**kwargs`, the parser fails with an `AttributeError`.

Please consider the following example (`example.enaml`):

```python
from enaml.widgets.api import *

def foobar(first=1, second=2, **kwargs):
    pass


enamldef Main(Window):
    title = 'Enaml bug'
```

When executing it using `enaml-run example.enaml` it should exit with the following error traceback:

```
Traceback (most recent call last):
  File "/Users/gabriel/anaconda/anaconda/envs/enaml_bug/bin/enaml-run", line 6, in <module>
    sys.exit(enaml.runner.main())
  File "/Users/gabriel/anaconda/anaconda/envs/enaml_bug/lib/python2.7/site-packages/enaml/runner.py", line 46, in main
    ast = parse(enaml_code, filename=enaml_file)
  File "/Users/gabriel/anaconda/anaconda/envs/enaml_bug/lib/python2.7/site-packages/enaml/core/parser/__init__.py", line 48, in parse
    return _parser.parse(enaml_source, filename)
  File "/Users/gabriel/anaconda/anaconda/envs/enaml_bug/lib/python2.7/site-packages/enaml/core/parser/base_parser.py", line 245, in parse
    return self.parser.parse(source, debug=0, lexer=lexer)
  File "/Users/gabriel/anaconda/anaconda/envs/enaml_bug/lib/python2.7/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/gabriel/anaconda/anaconda/envs/enaml_bug/lib/python2.7/site-packages/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/Users/gabriel/anaconda/anaconda/envs/enaml_bug/lib/python2.7/site-packages/enaml/core/parser/base_parser.py", line 3356, in p_varargslist18
    p[0] = self._make_args(args, defaults=defaults, kwarg=p[7])
  File "/Users/gabriel/anaconda/anaconda/envs/enaml_bug/lib/python2.7/site-packages/enaml/core/parser/parser2.py", line 204, in _make_args
    tok = FakeToken(self.lexer.lexer, kwarg.lineno)
AttributeError: type object 'Python2EnamlLexer' has no attribute 'lexer'
``` 

I have similar code that used to work fine on version `0.9.8` of `enaml`.

What is interesting is that if I define the function `foobar` as follows by removing one of the keyword argument defaults it works fine:

```
def foobar(first=1, **kwargs):
    pass
```

I haven't debugged and/or investigated the problem yet.

@sccolbert @MatthieuDartiailh if you have an idea or can point me in the right direction I'd be more than happy to contribute with a fix.

Gabe

**Comment by frmdstryr** [comment]
This [fix/hack](https://github.com/frmdstryr/enaml/commit/3f92ef7e27b2b8620cdd6ce8b0f0061afc41057f)  only works for py2 and I'm not sure it is the correct way to fix the error as I tried something similar with py3 but it doesn't work.

For py3 the exception is:

```
Traceback (most recent call last):
  File "/home/jrm/Workspace/enaml/venv3/bin/enaml-run", line 11, in <module>
    load_entry_point('enaml==0.10.2.dev0', 'console_scripts', 'enaml-run')()
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/runner.py", line 47, in main
    code = EnamlCompiler.compile(ast, enaml_file)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/enaml_compiler.py", line 180, in compile
    return compiler.visit(node)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/enaml_ast.py", line 351, in visit
    result = visitor(node, *args, **kwargs)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/enaml_compiler.py", line 196, in visit_Module
    self.visit(item)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/enaml_ast.py", line 351, in visit
    result = visitor(node, *args, **kwargs)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/enaml_compiler.py", line 214, in visit_PythonModule
    cg.insert_python_block(node.ast)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/code_generator.py", line 402, in insert_python_block
    code = compile(pydata, self.filename, mode='exec')
TypeError: required field "arg" missing from arg

``` 



For the good case:
```
def foobar(first=1, **kwargs):
    pass

```

![image](https://user-images.githubusercontent.com/380158/35177406-20da6f66-fd4d-11e7-85cf-f6e94a5bd179.png)

For the failing case:
```
def foobar(first=1, second=2,  **kwargs):
    pass

```

![image](https://user-images.githubusercontent.com/380158/35177428-4e58b9d4-fd4d-11e7-8385-d85f20e2777e.png)


The real problem is that for some reason ply/yacc is giving a LexToken (string) of NAME instead of the YaccSymbol (ast.Name).

**Comment by MatthieuDartiailh** [comment]
Looks like I messed up something in the parser (and Python 2 lexer perhaps too). I will give it a look. If you want to dig deeper by yourself look at the parser rules for functions definitions (in base_parser).

**Comment by MatthieuDartiailh** [comment]
Closed by #252
